# Generated by Django 3.1.2 on 2020-11-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='wilmer', max_length=30, verbose_name='nombre model prueba')),
                ('descrips', models.CharField(default='escriba su descripcion', max_length=30, verbose_name='descripcion')),
            ],
        ),
    ]
