# Generated by Django 3.1.2 on 2020-11-04 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_userr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userr',
        ),
    ]
