# Generated by Django 3.1.2 on 2020-11-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0002_auto_20201107_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='cantidad_periodicidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad Periodicidad'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='periodicidad',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Diaria', 'Diaria')], default='Mensual', max_length=7),
        ),
    ]
