# Generated by Django 3.1.2 on 2020-11-08 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0003_auto_20201107_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenar_indicador',
            name='analisis',
            field=models.TextField(null=True, verbose_name='Analisis'),
        ),
        migrations.AddField(
            model_name='lenar_indicador',
            name='observacion',
            field=models.TextField(null=True, verbose_name='Analisis'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indicador.cargo', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='periodicidad',
            field=models.CharField(choices=[('Diaria', 'Diaria'), ('Mensual', 'Mensual')], default='Mensual', max_length=7),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='tendencia_ascendente',
            field=models.CharField(choices=[('Ascendente', 'Ascendente'), ('Descendente', 'Descendente')], default='Ascendente', max_length=11),
        ),
    ]
