# Generated by Django 3.1.2 on 2020-11-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0004_auto_20201108_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_mejoramiento',
            name='cuento_costara',
            field=models.FloatField(null=True, verbose_name='¿Cuanto Costará ?'),
        ),
        migrations.AddField(
            model_name='plan_mejoramiento',
            name='titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='periodicidad',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Diaria', 'Diaria')], default='Mensual', max_length=7),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='tendencia_ascendente',
            field=models.CharField(choices=[('Descendente', 'Descendente'), ('Ascendente', 'Ascendente')], default='Ascendente', max_length=11),
        ),
    ]
