# Generated by Django 3.1.2 on 2020-11-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0006_auto_20201108_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='periodicidad',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Diaria', 'Diaria')], default='Mensual', max_length=7),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='tendencia_ascendente',
            field=models.CharField(choices=[('Ascendente', 'Ascendente'), ('Descendente', 'Descendente')], default='Ascendente', max_length=11),
        ),
    ]
