# Generated by Django 3.1.2 on 2020-11-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0007_auto_20201108_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='periodicidad',
            field=models.CharField(choices=[('Diaria', 'Diaria'), ('Mensual', 'Mensual')], default='Mensual', max_length=7),
        ),
        migrations.AlterField(
            model_name='oportunidad_ejecucion',
            name='oport_ejec',
            field=models.CharField(max_length=70, verbose_name='Oportunidad de Ejecución'),
        ),
    ]
