# Generated by Django 3.1.2 on 2020-11-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0008_auto_20201108_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='tendencia_ascendente',
            field=models.CharField(choices=[('Descendente', 'Descendente'), ('Ascendente', 'Ascendente')], default='Ascendente', max_length=11),
        ),
    ]
